# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('color', models.IntegerField()),
                ('size', models.IntegerField()),
                ('cost_of_piece', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_pieces', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=150)),
                ('account_iban_number', models.IntegerField()),
                ('clothes', models.ManyToManyField(to='crmsystem.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=150)),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Legal_person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('ico', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=30)),
                ('designer_surname', models.CharField(max_length=30)),
                ('name_of_mark', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('some_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Customer')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Physical_person',
            fields=[
                ('physical_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='legal_person',
            name='physical_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Physical_person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marks',
            field=models.ManyToManyField(to='crmsystem.Mark'),
        ),
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Employee'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Mark'),
        ),
    ]
