# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('color', models.IntegerField()),
                ('size', models.IntegerField()),
                ('cost_of_piece', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_pieces', models.IntegerField()),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Cloth')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('street_name', models.CharField(max_length=150)),
                ('account_iban_number', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=150)),
                ('street_number', models.PositiveSmallIntegerField()),
                ('street_name', models.CharField(max_length=150)),
                ('telephone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('title', models.CharField(choices=[('Bc.', 'Bc.'), ('Ing.', 'Ing.'), ('Mgr.', 'Mgr.'), ('PhDr.', 'PhDr.'), ('PaedDr.', 'PaedDr.'), ('RNDr.', 'RNDr.'), ('MUDr.', 'MUDr.'), ('PhD.', 'PhD.')], max_length=10)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Legal_person',
            fields=[
                ('ico', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=30)),
                ('designer_surname', models.CharField(max_length=30)),
                ('name_of_mark', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('customer', models.ManyToManyField(to='crmsystem.Customer')),
                ('employee', models.ManyToManyField(to='crmsystem.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='marks',
            field=models.ManyToManyField(to='crmsystem.Mark'),
        ),
        migrations.AddField(
            model_name='customer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Legal_person'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Employee'),
        ),
        migrations.AddField(
            model_name='contain',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Contract'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Mark'),
        ),
    ]
