# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloth',
            options={'permissions': (('show_cloth', 'Can show cloth'),)},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'permissions': (('show_contract', 'Can show contract info'),)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('edit_customer_info', 'Can edit info without assignment'), ('assign_employee', 'Can assign employee to customer'), ('show_customer', 'Can show customer info'))},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('show_employee', 'Can show employee info'),)},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'permissions': (('show_mark', 'Can show mark'),)},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'permissions': (('show_mtg', 'Can show meeting info'),)},
        ),
        migrations.AlterField(
            model_name='cloth',
            name='cost_of_piece',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='contain',
            name='num_of_pieces',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='legal_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crmsystem.Legal_person'),
        ),
    ]
