# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0002_auto_20171012_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('set_date', 'Can set date'),)},
        ),
    ]
