# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0002_auto_20171027_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'permissions': (('show_meeting', 'Can show meeting info'),)},
        ),
    ]
